#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if ! which ansible-playbook > /dev/null 2>&1; then
  echo "Could not find ansible. Please install ansible first"
  exit 1
fi

BASEDIR=$(dirname "$0")

if [ ! -f "${BASEDIR}/vars.yml" ]; then
  echo -n "mail: "
  read MAIL

  echo -n "displayName: "
  read DISPLAY_NAME

  echo -n "gpg key: "
  read GPG_KEY

  cat > "${BASEDIR}/vars.yml" <<EOF
mail: ${MAIL}
displayName: ${DISPLAY_NAME}
gpgKey: "${GPG_KEY}"
EOF
fi

if which python3 > /dev/null 2>&1; then
  PYTHON=$(which python3)
else
  PYTHON=$(which python)
fi

echo "starting ansible ..."
echo "===================="

# If you pass "-e ansible_become_pass=<your sudo password" it will not ask for the password.
# This is discouraged and only for testing purposes
ansible-playbook \
  -e ansible_python_interpreter="${PYTHON}" \
  --extra-vars="@${BASEDIR}/vars.yml" \
  "${BASEDIR}/playbook.yml" \
  --connection local \
  -i localhost, \
  $( [[ ! " $* " == *ansible_become_pass* ]] && echo '-K') \
  $@
