#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if ! which ansible-playbook > /dev/null 2>&1; then
  echo "Could not find ansible. Please install ansible first"
  exit 1
fi

BASEDIR=$(dirname "$0")

# TODO check if we need vars
#if [ ! -f "${BASEDIR}/vars.yml" ]; then
#  echo -n "mail: "
#  read MAIL
#
#  echo -n "displayName: "
#  read DISPLAY_NAME

#  echo -n "gpg key (KeyId): "
#  read GPG_KEY

#  cat > "${BASEDIR}/vars.yml" <<EOF
#mail: ${MAIL}
#displayName: ${DISPLAY_NAME}
#gpgKey: "${GPG_KEY}"
#EOF
#fi

if which python3 > /dev/null 2>&1; then
  PYTHON=$(which python3)
else
  PYTHON=$(which python)
fi

echo "starting ansible ..."
echo "===================="

ansible-playbook \
  -e ansible_python_interpreter="${PYTHON}" \
  "${BASEDIR}/playbook.yml" \
  --connection local \
  -i localhost, \
  -K $@

# TODO check if we need vars
#  --extra-vars="@${BASEDIR}/vars.yml" \
