- name: Install yadm (MacOSX)
  homebrew:
    name:
    - yadm
  when: ansible_distribution == "MacOSX"

- name: Install yadm (Ubuntu)
  become: True
  apt:
    name: yadm
  when: ansible_distribution == "Ubuntu"

- name: Clone dotfiles repo
  command: "yadm clone {{ dotfiles_repo_url }}"
  args:
    creates: ~/.local/share/yadm/repo.git
  register: clone

# in some cases yadm doesn't clone the repo correctly
# it shows all files as deleted
- name: Reset git repository
  command: "yadm reset --hard"
  when: clone.changed
