- name: Install k8s tools (Ubuntu)
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install k8s tools (MacOSX)
  import_tasks: osx.yml
  when: ansible_distribution == "MacOSX"
