- name: Install zsh and required dependencies (MacOSX)
  homebrew:
    name:
    - zsh
    - fzf
    - starship
  when: ansible_distribution == "MacOSX"

- name: Install zsh and required dependencies (Ubuntu)
  become: True
  apt:
    name:
    - zsh
    - fzf
  when: ansible_distribution == "Ubuntu"

- name: Install starship (Ubuntu)
  import_tasks: starship_linux.yml
  when: ansible_distribution == "Ubuntu"

- name: Find path of zsh
  shell: which zsh
  register: whichzsh
  changed_when: False

- name: Change default shell to zsh
  become: True
  user:
    name: "{{ lookup('env','USER') }}"
    shell: "{{ whichzsh.stdout }}"
  when: not ansible_check_mode

- name: Install terminal font (Linux)
  import_tasks: font_linux.yml
  when: ansible_distribution == "Ubuntu"

- name: Install terminal font (MacOSX)
  import_tasks: font_osx.yml
  when: ansible_distribution == "MacOSX"

- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    update: no

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    update: no

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    update: no
