- name: Install git and related tools (MacOSX)
  homebrew:
    name:
    - git
    - git-crypt
    - git-lfs
    - gh
  when: ansible_distribution == "MacOSX"

- name: Install git and related tools (Ubuntu)
  become: True
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
