- name: Install tmux (Ubuntu)
  become: True
  apt:
    name: tmux
  when: ansible_distribution == "Ubuntu"

- name: Install tmux and required dependencies (MacOSX)
  homebrew:
    name: tmux
  when: ansible_distribution == "MacOSX"

- name: Install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  register: tpm

- name: Install tmux plugins
  shell: |
    # start a server but don't attach to it
    tmux start-server
    # create a new session but don't attach to it either
    tmux new-session -d
    # install the plugins
    ~/.tmux/plugins/tpm/scripts/install_plugins.sh
    # killing the server is not required, I guess
    tmux kill-server
  when: tpm.changed
