- name: Install docker (Linux)
  import_tasks: ubuntu.yml
  when: ansible_system == "Linux"

- name: Install docker (MacOSX)
  homebrew_cask:
    name: docker-edge # is this docker-desktop?
  when: ansible_distribution == "MacOSX"
