- name: Install docker gpg key (Ubuntu)
  become: True
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker.gpg

- name: Capture lsb release (Ubuntu)
  shell: lsb_release -cs
  register: lsbrelease
  changed_when: False

- name: Get dpkg architecture (Ubuntu)
  command:
    cmd: "dpkg --print-architecture"
  register: dpkg_arch
  changed_when: false

- name: Install docker stable apt repository (Ubuntu)
  become: True
  apt_repository:
    repo: deb [arch={{ dpkg_arch.stdout }} signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ lsbrelease.stdout }} stable

- name: Install docker packages (Ubuntu)
  become: True
  apt:
    name: 
    - docker-ce
    - docker-compose-plugin

- name: Start and enable docker daemon
  become: True
  systemd:
    name: docker.service
    enabled: True
    state: started

- name: Add user to docker group
  become: True
  user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: True

