- name: Install gpg and related tools (MacOSX)
  homebrew:
    name:
    - gnupg
    - pinentry-mac
  when: ansible_distribution == "MacOSX"

- name: Install gpg and related tools (Ubuntu)
  become: True
  apt:
    name:
    - gnupg
    - pcscd
    - scdaemon
  when: ansible_distribution == "Ubuntu"
